import styles from "./NutritionPlanSummary.module.css";

function NutritionPlanSummary({
  plan,
  loading,
  onAddNew,
  onEdit,
  onDelete,
}) {
  if (loading) {
    return (
      <section className={styles.card}>
        <div className={styles.loading}>
          Loading nutrition plan...
        </div>
      </section>
    );
  }

  if (!plan) {
    return (
      <section className={styles.card}>
        <div className={styles.empty}>
          <span className={styles.eyebrow}>
            NUTRITION PLAN
          </span>

          <h2>No Nutrition Plan Yet</h2>

          <p>
            Create a nutrition plan to start
            tracking your nutrition.
          </p>

          {onAddNew && (
            <button
              className={styles.primaryButton}
              onClick={onAddNew}
            >
              + Create Nutrition Plan
            </button>
          )}
        </div>
      </section>
    );
  }

  return (
    <section className={styles.card}>
      <div className={styles.header}>
        <div>
          <span className={styles.eyebrow}>
            CURRENT PLAN
          </span>

          <h2>{plan.plan_name}</h2>

          <p>
            {formatDate(plan.start_date)}

            {plan.end_date
              ? ` → ${formatDate(
                  plan.end_date
                )}`
              : ""}
          </p>
        </div>

        <div className={styles.actions}>
          {onEdit && (
            <button
              type="button"
              className={styles.editButton}
              onClick={() => onEdit(plan)}
            >
              Edit
            </button>
          )}

          {onDelete && (
            <button
              type="button"
              className={
                styles.deleteButton
              }
              onClick={() =>
                onDelete(plan)
              }
            >
              Delete
            </button>
          )}
        </div>
      </div>

      <div className={styles.meta}>
        <span>
          Goal:{" "}
          <strong>
            {formatGoal(plan.goal)}
          </strong>
        </span>

        <span>
          Generated by:{" "}
          <strong>
            {plan.generated_by}
          </strong>
        </span>
      </div>

      <div className={styles.targets}>
        <Target
          label="Calories"
          value={
            plan.daily_calorie_target
          }
          unit="kcal"
        />

        <Target
          label="Protein"
          value={
            plan.daily_protein_target_g
          }
          unit="g"
        />

        <Target
          label="Carbohydrates"
          value={
            plan.daily_carbohydrate_target_g
          }
          unit="g"
        />

        <Target
          label="Fat"
          value={
            plan.daily_fat_target_g
          }
          unit="g"
        />
      </div>

      {plan.notes && (
        <div className={styles.notes}>
          <strong>Notes</strong>

          <p>{plan.notes}</p>
        </div>
      )}

      <div className={styles.mealHeader}>
        <h3>Meals</h3>

        <span>
          {plan.meals?.length || 0} meals
        </span>
      </div>

      <div className={styles.mealList}>
        {plan.meals?.map(
          (meal, index) => (
            <div
              className={styles.meal}
              key={
                meal._id || index
              }
            >
              <div
                className={
                  styles.mealNumber
                }
              >
                {index + 1}
              </div>

              <div
                className={styles.mealInfo}
              >
                <h4>
                  {meal.meal_name}
                </h4>

                <div
                  className={
                    styles.foods
                  }
                >
                  {meal.foods?.map(
                    (
                      food,
                      foodIndex
                    ) => (
                      <span
                        key={
                          foodIndex
                        }
                      >
                        {food}
                      </span>
                    )
                  )}
                </div>

                <div
                  className={
                    styles.mealStats
                  }
                >
                  {meal.calories_kcal !==
                    undefined && (
                    <span>
                      {
                        meal.calories_kcal
                      }{" "}
                      kcal
                    </span>
                  )}

                  {meal.protein_g !==
                    undefined && (
                    <span>
                      {
                        meal.protein_g
                      }{" "}
                      g protein
                    </span>
                  )}

                  {meal.carbohydrates_g !==
                    undefined && (
                    <span>
                      {
                        meal.carbohydrates_g
                      }{" "}
                      g carbs
                    </span>
                  )}

                  {meal.fat_g !==
                    undefined && (
                    <span>
                      {meal.fat_g} g fat
                    </span>
                  )}
                </div>
              </div>
            </div>
          )
        )}
      </div>
    </section>
  );
}

function Target({
  label,
  value,
  unit,
}) {
  return (
    <div className={styles.target}>
      <span>{label}</span>

      <strong>
        {value} {unit}
      </strong>
    </div>
  );
}

function formatGoal(goal) {
  const labels = {
    weight_loss: "Weight Loss",
    muscle_gain: "Muscle Gain",
    maintenance: "Maintenance",
    recomposition: "Recomposition",
  };

  return labels[goal] || goal;
}

function formatDate(value) {
  if (!value) {
    return "—";
  }

  const date = new Date(value);

  if (Number.isNaN(date.getTime())) {
    return value;
  }

  return date.toLocaleDateString(
    "en-US",
    {
      year: "numeric",
      month: "short",
      day: "numeric",
    }
  );
}

export default NutritionPlanSummary;